package main

import "gbe/stringfunctions"

func main() {
	//fmt.Println("hello world")
	//values.Values()
	//variables.Variables()
	//constants.Constants()
	//forloop.ForLoop()
	//ifelse.IfElse()
	//switchexample.Switch()
	//arrays.Arrays()
	//slicesexample.SlicesEx()
	//mapsexample.MapsExample()
	//functions.Functions()
	//mrv.Mrv()
	//variadic.Variadic()
	//closure.Closure()
	//recursion.Recursion()
	//rangeover.RangeOver()
	//pointers.Pointers()
	//stringsrunes.StringsRunes()
	//structexample.StructExample()
	//methods.Methods()
	//intface.IntFace()
	//enums.Enums()
	//structembed.StructEmbed()
	//generics.Generics()
	//iterator.Iterator()
	//errorexample.ErrorExample()
	//goroutines.GoRoutines()
	//channels.Channels()
	//chsync.ChSync()
	//selectexample.SelectExample()
	//timeouts.Timeouts()
	//closechan.CloseChan()
	//rangechan.RangeChan()
	//ratelimiting.RateLimiting()
	//atomicexample.AtomicExample()
	//mutexes.Mutexes()
	//statefulgo.StatefulGo()
	//sorting.Sorting()
	//sortfunction.SortFunction()
	//panicexample.PanicExample()
	//recoverexample.RecoverExample()
	stringfunctions.StringFunctions()
}
